from typing import Protocol


class IObjectStorage(Protocol):
    async def upload(self, local_path: str, key: str) -> None: ...
    async def download(self, key: str, local_path: str) -> bool: ...
    async def delete(self, key: str) -> None: ...
    async def list_keys(self, prefix: str) -> list[str]: ...
