"""Pydantic input schemas for geo intersection endpoints."""

from datetime import datetime, timezone
from typing import Any, Dict, Optional

from pydantic import (
    BaseModel,
    Field,
    field_serializer,
    field_validator,
    model_validator,
)


class GeoJSONInput(BaseModel):
    """Pydantic model for validating GeoJSON input (Geometry, Feature, or FeatureCollection)."""

    model_config = {"extra": "allow"}

    type: str

    @model_validator(mode="before")
    @classmethod
    def validate_geojson(cls, v: Any) -> Any:
        """Validate that the input is a dict with a 'type' field."""
        if not isinstance(v, dict):
            raise ValueError("Input must be a GeoJSON object")
        if not v.get("type"):
            raise ValueError("Missing 'type' field in GeoJSON")
        return v

    def extract_geometry(self) -> Dict[str, Any]:
        """Extract the geometry dict from any GeoJSON wrapper type."""
        data = self.model_dump()
        geojson_type = data.get("type", "").lower()

        if geojson_type == "featurecollection":
            features = data.get("features", [])
            if not features:
                raise ValueError("FeatureCollection is empty")
            return features[0].get("geometry") or {}
        if geojson_type == "feature":
            return data.get("geometry") or {}
        return data


class AlertCreateRequest(BaseModel):
    """Request body for generating a weather alert."""

    phenomenon_code: int = Field(
        ..., ge=1, le=92, description="Weather phenomenon code (1-92)"
    )
    geojson: GeoJSONInput


class Phenomenon(BaseModel):
    """Model for a weather phenomenon."""

    code: int
    description: Optional[str]


class AlertLimits(BaseModel):
    """Limits for alert generation derived from the database schema."""

    max_vertex_count: int


class AlertSummary(BaseModel):
    """Summary of an active alert from the external taviso table.

    The taviso datetimes are stored in UTC but are timezone-naive in the DB, so
    they are interpreted as UTC and serialized with a trailing 'Z'.
    """

    alert_id: int
    phenomenon: str
    area: str
    polygon: str
    start_datetime: datetime
    end_datetime: datetime

    @field_validator("start_datetime", "end_datetime", mode="before")
    @classmethod
    def _assume_utc(cls, value: Any) -> Any:
        """Interpret naive datetimes coming from the DB as UTC."""
        if isinstance(value, datetime) and value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)
        return value

    @field_serializer("start_datetime", "end_datetime")
    def _serialize_utc_z(self, value: datetime) -> str:
        """Serialize as ISO-8601 in UTC with a trailing 'Z'."""
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


class AlertJobAccepted(BaseModel):
    """Body returned by `POST /alerts` (202) when a job is accepted.

    Generation runs in the background; poll `GET /alerts/jobs/{job_id}` for the
    outcome. The echoed `phenomenon` and `polygon` let the client render an
    optimistic "processing" placeholder before the alert is generated.
    """

    job_id: str
    phenomenon_code: int
    phenomenon: str
    polygon: str


class AlertJobStatus(BaseModel):
    """Status of a background alert generation job.

    `status` is one of queued | processing | done | failed. On `done`,
    `alert_id` is the generated `IdAviso_temporal`. On `failed`, `error_code`
    is a stable machine-readable reason (e.g. `area_too_large`) and `error` a
    human-readable message.
    """

    job_id: str
    status: str
    alert_id: Optional[int] = None
    error_code: Optional[str] = None
    error: Optional[str] = None


class PendingAlertSummary(BaseModel):
    """Summary of a pending alert from the `taviso_temporal` table.

    Pending alerts are rows with `Procesado='N'` — generated by POST /alerts but
    not yet mirrored into `taviso`. The GIF URLs follow the same format the
    generation endpoint returns: `/alerts/{filename}`.
    """

    alert_id: int
    phenomenon: str
    area: str
    polygon: str
    gif_gral_url: str
    gif_area_url: str
